(load "/Users/aayushshrestha/Desktop/LispProject/board.lisp")
(load "/Users/aayushshrestha/Desktop/LispProject/CoinToss.lisp")
(load "/Users/aayushshrestha/Desktop/LispProject/Round.lisp")
; human and computer both store data in this way
; (colour totalPoints Points CapturePoints TotalMoves) => ("W" 0 0 0 0 0)
(defun doesUserWantToLoadGame ()
  (princ "Do you want to load the game? Please enter \"N\" for 'No' and \"Y\" for 'Yes': ")
  (terpri)
  (let ((input (string-upcase (read))))
    (cond
      ((string= input "Y") (StartFromLoadedGame))
      ((string= input "N") (StartNewGame))
      (t (doesUserWantToLoadGame)))))
(defun StartFromLoadedGame()
  (print "Please enter a valid file path")
)
(defun startNewGame ()
  (princ "Starting a new game ")
  (terpri)
  (print "TESTING 1: CALCULATE Capture POINT")
  (terpri)
  (let* ((board (GetEmptyBoard))
         (board1 (InsertPiece board 0 0 "B"))
         (board2 (InsertPiece board1 1 1 "W"))
         (board3 (InsertPiece board2 2 2 "W"))
         (CapturePointAndNewBoard (CalculateTotalCapturePoint 3 3 "B" board3 0 0)))
         (PrintBoardWithIndex (rest CapturePointAndNewBoard))
         (terpri)
         (print "New score: ")
         (princ (first(CapturePointAndNewBoard)))
  )
)
(defun startNewGame ()
  (princ "Starting a new game ")
  (terpri)
  (print "TESTING 2: Calculate Capture score")
  (terpri)
  (let* ((board (GetEmptyBoard))
         (board1 (InsertPiece board 0 0 "B"))
         (board2 (InsertPiece board1 1 1 "W"))
         (board3 (InsertPiece board2 2 2 "W"))
         (newBoardAndPlayer (GetNewBoardAndPoints 3 3 `("B" 0 0 0 0) board3)))
         (PrintBoardWithIndex (first capturePointAndNewBoard))
         (terpri)
         (print "colour totalPoints Points Capture and TotalMoves")
         (print (rest newBoardAndPlayer))
  )
)
(doesUserWantToLoadGame)
