(defun test1()
(print "TESTING 1: CALCULATE Capture POINT")
  (terpri)
  (let ((board (GetEmptyBoard)))
    (let ((board1 (InsertPiece board 0 0 "B")))
      (let ((board2 (InsertPiece board1 1 1 "W")))
        (let ((board3 (InsertPiece board2 2 2 "W")))
         (PrintBoardWithIndex board3)
         (print (CaptureLtDiagonalUp 3 3 "B" board3))
        )
      )
    )
  )
)